### ISSUE TITLE
Bump dependency ``binary``

### ISSUE THREAD

**Issue by tindzk** [kawu/sgd#1]
cabal tries to pull in an old version of `binary` which is conflicting with others. As the API did not change, it is safe to bump the dependency.

**Comment by kawu** [comment]
I recently updated the library and I am now going through the issues I failed to react to in the past (sorry for that...).  The reported dependency issue should have been solved by now.

**Comment by tindzk** [comment]
No problem. I will close the issue as it has been resolved.
