### ISSUE TITLE
Reference for the algorithm?

### ISSUE THREAD

**Issue by nanonaren** [kawu/sgd#3]
Hi, could you please add the reference for the source of the algorithm (or just point me to it here?). I am trying to understand why you are storing the gradients in the log-domain. Thanks.

**Comment by kawu** [comment]
Sorry for a complete lack of reaction on my part, I was extremely busy at the time you filed the issue; better extremely late than never, I guess...

I returned to this library a couple of months ago and changed it significantly.  I added the references in the process so this should not be an issue any more.

In any case, your question about storing the gradients in the log-domain was a good one.  To be honest, I'm not sure now this design decision was well justified.  It made sense in my particular application (training conditional random fields with sparse features), but this should probably be abstracted over.  As it is in the new version of the library, where the set of parameters (as well as the gradient) is represented using a type class (`ParamSet`).
