### ISSUE TITLE
Update to use latest hmatrix

### ISSUE THREAD

**Issue by AlexeyRaga** [kawu/sgd#8]
The current (on hackage) version of SGD requires `hmatrix-0.19`. 
Would it be possible to get a support for the latest version of `hmatrix`?

**Comment by kawu** [comment]
Thanks for the info.  I've just bumped the hmatrix dependency and uploaded the new version of the library to hackage, it should work with `hmatrix-0.20`.

**Comment by AlexeyRaga** [comment]
Thanks!
